networks:
    vama-web-dev:
        driver: bridge
    traefik-proxy-vama-local:
        external: true

services:
    app:
        image: node:22-bullseye-slim
        command: sh -c "npm run dev"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.vama-web-http-router.rule=Host(`${APP_URL:-vama-web.localhost}`)"
            - "traefik.http.routers.vama-web-http-router.entrypoints=web"
        container_name: vama-web-app-dev
        working_dir: /application
        volumes:
            - .:/application
        ports:
            - ${DOCKER_APP_HOST_PORT:-25575}:${TRAEFIK_PORT:-80}
        networks:
            - vama-web-dev
            - traefik-proxy-vama-local
        restart: no
